name: 'git-restore-mtime'
description: "Restore file's modified time (timestamp) based on git commits"
author: 'Pixelcop Research, Inc.'
inputs:
  working-directory:
    description: "Where to run the action"
    required: false
    default: '.'
  args:
    description: "Command line arguments to pass to git-restore-mtime"
    required: false
    default: ''
branding:
  icon: 'clock'
  color: 'orange'
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        cd "${{ inputs.working-directory }}" && "$GITHUB_ACTION_PATH"/git-restore-mtime ${{ inputs.args }}
